package com.example.appthitracnghiem.utils

object PreferenceKey {
    const val KEY_FIRST_INSTALL = "KEY_FIRST_INSTALL"
    const val KEY_USER_LOGGED_IN = "KEY_USER_LOGGED_IN"
    const val AUTHORIZATION = "AUTHORIZATION"
    const val USER_EMAIL = "USER_EMAIL"
    const val USER_PASSWORD = "USER_PASSWORD"
    const val SAVE_ACCOUNT = "SAVE_ACCOUNT"
    const val USER_ID = "USER_ID"
    const val TIME_EXAM = "TIME_EXAM"
    const val USER_NAME = "USER_NAME"
    const val USER_AVATAR = "USER_AVATAR"
    const val TYPE = "TYPE"
    const val START_DO_TEST = "START_DO_TEST"
    const val CREATE_STATUS = "STATUS"
    const val CREATE_DEPARTMENT = "CREATE_DEPARTMENT"
    const val CREATE_TITLE = "CREATE_TITLE"
    const val CREATE_DESCRIBE_QUIZ = "CREATE_DESCRIBE_QUIZ"
    const val EXAM_ID_HISTORY = "EXAM_ID_HISTORY"
    const val ID_DEPARTMENT = "ID_DEPARTMENT"
    const val LIST_CREATE_QUESTION_EXAM = "LIST_CREATE_QUESTION_EXAM"
    const val LIST_CREATE_NUMBER_QUESTION = "LIST_CREATE_NUMBER_QUESTION"
    const val CREATE_SUBJECT_ID = "CREATE_SUBJECT_ID"
    const val CREATE_URI_IMAGE_SUBJECT = "CREATE_URI_IMAGE_SUBJECT"
}